svr_config:
  name: "relationsvr"
  host: 121.43.102.177
  port: 8081
  mode: release
  user_svr_name: "usersvr"

mysql:
  host: 121.43.102.177
  port: 8086
  database: camps_tiktok
  username: root
  password: 123456

minio:
  #minio服务主机ip，需要填具体ip
  host: 121.43.102.177
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  videobuckets: video
  picbuckets: pic

redis:
  address: 192.168.1.12
  network: tcp
  port: 6379
  auth: 123

log:
  level: "info"
  file_name: ".log"
  log_path: "../log/relationsvr/"
  max_size: 50
  max_age: 20
  MaxBackups: 10

consul:
  host: 121.43.102.177
  port: 8090
  tags:
    - "relationsvr"

