mysql:  
  host: 192.168.1.12
  port: 3306
  database: TikTokLite
  username: user
  password: 123
minio:
  #minio服务主机ip，需要填具体ip
  host: 192.168.1.12
  port: 9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  videobuckets: video
  picbuckets: pic
redis:
  address: 192.168.1.12
  network: tcp
  port: 6379
  auth: 123
videofile: /tmp/file/video/
logfile: /tmp/file/log/
picfile: /tmp/file/picture/
level: info


//    Addr:               "localhost:6379",
                            Password:           "", // no password set
                            DB:                 0,  // use default DB
                            MaxRetries:         3,  // set maximum number of retries
                            DialTimeout:        5 * time.Second, // set dial timeout
                            ReadTimeout:        3 * time.Second, // set read timeout
                            WriteTimeout:       3 * time.Second, // set write timeout
                            PoolSize:           10, // set connection pool size
                            MinIdleConns:       5,  // set minimum idle connections
                            IdleTimeout:        240 * time.Second, // set idle timeout
                            MaxConnAge:         300 * time.Second, // set maximum connection age
                            PoolTimeout:        5 * time.Second,   // set pool timeout
                            IdleCheckFrequency: 60 * time.Second,  // set idle c