svr_config:
  name: "commentsvr"
  host: "43.139.192.217"
  port: "8005"
  user_svr_name: "usersvr"


redis:
  host: "43.139.192.217"
  password: "123456"
  db: 0
  port: 6379
  PoolSize: 10

mysql:
  host: 121.43.102.177
  port: 8086
  database: camps_tiktok
  username: root
  password: 123456

log:
  level: "debug"
  filename: "comment.log"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "43.139.192.217"
  port: 8500
  tags:
    - "commentsvr"

