svr_config:
  name: "gatewaysvr"
  host: "43.139.192.217"
  port: "8006"
  mode: "dev"
  user_svr_name: "usersvr"
  video_svr_name: "videosvr"
  favorite_svr_name: "favoritesvr"
  relation_svr_name: "relationsvr"
  comment_svr_name: "commentsvr"
  videopath: "/root/tiktok/store/video"

log:
  level: "debug"
  file_name: "gateway.log"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "43.139.192.217"
  port: 8500
  tags:
    - "gatewaysvr"